- hosts: all
  tasks:
    - name: Set password fact
      ansible.builtin.set_fact:
        password: "Test123ABC!"

    - name: Create hacluster user with a password
      ansible.builtin.user:
        name: hacluster
        password: "{{ password | password_hash('sha512') }}"

    - name: Ensure pcsd service is enabled
      ansible.builtin.systemd_service:
        name: pcsd.service
        state: started
        enabled: true
